basePath: /api/v1
definitions:
  user.RequestEmailCodeInput:
    properties:
      email:
        example: user@example.com
        type: string
    required:
    - email
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: documentation for be-tm api
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: be-tm api
  version: "1.0"
paths:
  /users/register/email-code/send:
    post:
      description: get verification email code
      parameters:
      - description: email for send verification code
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.RequestEmailCodeInput'
      produces:
      - application/json
      responses: {}
      summary: get verification email code
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
